var mongoose = require('mongoose');
var tree=require('mongoose-path-tree');
var Schema = mongoose.Schema;
var CategorySchema= new Schema({
	name:String,
	count:Number,
	facets:{type:[String]}
});
CategorySchema.plugin(tree, {
  pathSeparator : '/',              // Default path separator
  onDelete :      'REPARENT',       // Can be set to 'DELETE' or 'REPARENT'. Default: 'REPARENT'
  numWorkers:     5,                // Number of stream workers
  idType:         Schema.ObjectId,  // Type used for _id. Can be, for example, String generated by shortid module
});

module.exports = mongoose.model('categories', CategorySchema);


var Category=mongoose.model('categories', CategorySchema);
var jew = new Category({name:'Jewelry'});
var bracelets = new Category({name:'Bracelets'});
var neck = new Category({name:'Necklaces'});
bracelets.parent=jew;
neck.parent=jew;

jew.save(function(){
	neck.save();
});

